### ISSUE TITLE
Search Repository not returning results in redmine 3.2

### ISSUE THREAD

**Issue by woti6644** [xelkano/redmine_xapian#68] opened 2016-04-21 10:15 UTC
I have installed the latest version of the plugin and can index and search files but does not return any matches from the repository. I have checked through the log files and have found over 300 lines with 'Wrong format of the URL' as the error

**Comment by picman** [comment] 2016-04-21 10:22
Please post the log, at least a few of these lines with the error.

**Comment by woti6644** [comment] 2016-04-21 10:58
Starting redmine-mylyn-connector plugin for Redmine
Started GET "/search?utf8=%E2%9C%93&q=organisation&scope=all&all_words=&all_words=1&titles_only=&repofiles=1&commit=Submit" for 10.100.30.87 at 2016-04-20 17:03:32 +0100
Processing by SearchController#index as HTML
  Parameters: {"utf8"=>"✓", "q"=>"organisation", "scope"=>"all", "all_words"=>"1", "titles_only"=>"", "repofiles"=>"1", "commit"=>"Submit"}
  Current user: user1 (id=98)
Wrong format of the URL
Wrong format of the URL
Wrong format of the URL
Wrong format of the URL
Wrong format of the URL
Wrong format of the URL
Wrong format of the URL
Wrong format of the URL
Wrong format of the URL
Wrong format of the URL
Wrong format of the URL
  Rendered plugins/redmine_xapian/app/views/search/index.html.erb within layouts/base (33.9ms)
  Rendered plugins/advanced_roadmap/app/views/hooks/_stylesheet.html.erb (0.8ms)
  Rendered plugins/quick_view/app/views/hooks/_quick_view_base_head.html.erb (0.4ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (0.9ms)
  Rendered inline template (0.6ms)
  Rendered plugins/scrum/app/views/scrum_hooks/_head.html.erb (0.8ms)
  Rendered plugins/scrum/app/views/scrum_hooks/_scrum_tips.html.erb (19.4ms)
  Rendered plugins/redmine_banner/app/views/banner/_project_body_bottom.html.erb (0.8ms)
  Rendered plugins/quick_view/app/views/hooks/_quick_view_base_bottom_tooltip.html.erb (1.1ms)
  Rendered plugins/quick_view/app/views/hooks/_quick_view_base_bottom.html.erb (5.2ms)
  Rendered plugins/quick_view/app/views/hooks/_quick_view_base_bottom_worktime_ext.html.erb (1.1ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (1.5ms)
Completed 200 OK in 590ms (Views: 407.3ms | ActiveRecord: 24.4ms)

i have removed most of the Wrong format of the URL lines as there were over 1000 of them

**Comment by woti6644** [comment] 2016-04-21 11:16
i have increaced the logging level and for each Wrong format of the URL there is some extra data here is a example:

stemming_lang: english
stemming_strategy: STEM_SOME
databasepath: /var/omindex/repodb
query_string is: organisation*
Parsed query is: Xapian::Query((organisation:(pos=1) SYNONYM organisational:(pos=1) SYNONYM organisational_permission:(pos=1) SYNONYM organisational_permission_delete:(pos=1) SYNONYM organisationcode:(pos=1) SYNONYM organisationdao:(pos=1) SYNONYM organisationfacade:(pos=1) SYNONYM organisationmakingdecisionname:(pos=1) SYNONYM organisationname:(pos=1) SYNONYM organisations:(pos=1) SYNONYM organisations&keyword:(pos=1) SYNONYM organisations_tbl:(pos=1) SYNONYM organisationservice:(pos=1) SYNONYM organisationserviceimpl:(pos=1) SYNONYM organisationteamcode:(pos=1)))
Matches 1-1000 records:
Searching for repofiles
Repository file: /projects/cms/repository/entry/branches/CHP31/src/uk/co/test/cms/serviceimpl/OrganisationServiceImpl.java
Repository date: 2013-05-15 17:44:29 +0100
Repository sample field: package uk.co.test.cms.serviceimpl;  import java.util.List;  import org.springframework.beans.factory.annotation.Autowired; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;  import uk.co.test.cms.dao.OrganisationDao; import uk.co.test.cms.data.common.Organisation; import uk.co.test.cms.data.common.TeamCodes; import
Wrong format of the URL

**Comment by picman** [comment] 2016-04-22 12:03
The problem is that your repository has no identifier. I've re-added an info into the README file as follows:

"You have to take into account that the script needs a defined repository identifier for all repositories that will be indexed. The repository identifier is not required in redmine and can have null value for some of the repositories, so before indexing a repository you have to be sure that the repository has a defined identifier, otherwise the script will ignore it.

You can run this SQL statement in your database for setting up a default identifier for your repositories:"
```SQL
mysql> UDATE repositories SET identifier = 'main' WHERE identifier IS NULL;
```

**Comment by woti6644** [comment] 2016-04-22 13:17
Ok I have fixed the problem and reindexed the repository and i can search and get a return for the repositories now but when I click on next for the second page i am getting the following error

  Rendered plugins/redmine_xapian/app/views/search/index.html.erb within layouts/base (33.7ms)
Completed 500 Internal Server Error in 58ms (ActiveRecord: 7.9ms)

ActionView::Template::Error (invalid byte sequence in UTF-8):
    79:         <% # Plugin change end %>
    80:         </dt>        
    81:         <dd><span class="description">          
    82:           <%= highlight_tokens(e.event_description, @tokens) %>          
    83:         </span>        
    84:         <span class="author"><%= format_time(e.event_datetime) %></span></dd>
    85:       <% end %>
  app/helpers/search_helper.rb:26:in `split'
  app/helpers/search_helper.rb:26:in `highlight_tokens'
  plugins/redmine_xapian/app/views/search/index.html.erb:82:in `block in _plugins_redmine_xapian_app_views_search_index_html_erb__1745488145712991585_70337867539080'
  plugins/redmine_xapian/app/views/search/index.html.erb:68:in `each'
  plugins/redmine_xapian/app/views/search/index.html.erb:68:in `_plugins_redmine_xapian_app_views_search_index_html_erb__1745488145712991585_70337867539080'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'

**Comment by picman** [comment] 2016-04-25 11:32
Please try with devel-1.6.5.

**Comment by woti6644** [comment] 2016-04-29 12:26
I am still seeing the same error with devel-1.6.5

**Comment by picman** [comment] 2016-04-29 12:37
Could you send me the file you are searching in and the text you are searching for on my email, please?

**Comment by woti6644** [comment] 2016-05-03 16:26
I am still trying to work out which file is causing the error as I have indexed a large repo will cut it down and see if i can find the problem file.

**Comment by woti6644** [comment] 2016-05-04 11:18
i have found a £ sign in a file removing the file and reindexing fixes the error

**Comment by woti6644** [comment] 2016-05-04 11:51
in file lib/redmine_xapian/search_strategies/xapian_search.rb
i have edited line 183 the orignal text was 
repository_attachment.description = dochash[:sample].force_encoding('UTF-8') if dochash[:sample]
i have changed this to 
 repository_attachment.description = dochash[:sample].encode!('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '') if dochash[:sample]

now I do not see the error when searching

**Comment by picman** [comment] 2016-05-06 08:57
That's strange. I've just tested your modification. If I use the original code, it searches correctly the searched string and displayed £ in the sample code.

![no_replace](https://cloud.githubusercontent.com/assets/779003/15068415/699adcf2-1377-11e6-97d9-945e5b94ed21.png)

If I try your code, it searches correctly the searched string, however the £ in the sample code is replaced with ''

![replace](https://cloud.githubusercontent.com/assets/779003/15068421/70635dd4-1377-11e6-9bfc-32d848253602.png)

So your modification is not bad, however it can cause missing characters in the sample code.

Could you please try the following code in your environment, please? I've added _valid_encoding?_ check.

```ruby
#repository_attachment.description = dochash[:sample].force_encoding('UTF-8') if dochash[:sample]
  if dochash[:sample]    
    if dochash[:sample].valid_encoding?
      repository_attachment.description = dochash[:sample]
    else
      repository_attachment.description = dochash[:sample].encode('UTF-8', dochash[:sample].encoding,
      :invalid => :replace, :undef => :replace)
    end
  end
```

It keeps the Pound character in my sample code.

**Comment by woti6644** [comment] 2016-05-16 16:11
here is the file causing the issue 
[test.zip](https://github.com/xelkano/redmine_xapian/files/266465/test.zip)

I have added your updated code and it works fine the £ sign is removed by it think it is a problem with the encoding of the file.

now i am getting a different error 
Completed 500 Internal Server Error in 91ms (ActiveRecord: 51.2ms)

ActionView::Template::Error (undefined method `localtime' for Tue, 01 Nov 2011 10:08:24 +0000:DateTime):
    81:         <dd><span class="description">          
    82:           <%= highlight_tokens(e.event_description, @tokens) %>          
    83:         </span>        
    84:         <span class="author"><%= format_time(e.event_datetime) %></span></dd>
    85:       <% end %>
    86:     </dl>
    87: <% end %>

I am thinking this is relating to something in a different file will have a look later this week so see if i can narrow the culprit down

**Comment by picman** [comment] 2016-06-10 08:48
Thank you for the file.

1. If you open the file in an editor you can see that it contain invalid characters:

![repo_file](https://cloud.githubusercontent.com/assets/779003/15958871/46677172-2ef8-11e6-95e9-c21fde182638.png)

2. I've fixed the wrong encoding so as the application doesn't fail:
![2016-06-10_10-46-45](https://cloud.githubusercontent.com/assets/779003/15958971/c38c8a5c-2ef8-11e6-966a-0d923eacf803.png)

**Closed by picman** 2016-06-10 08:48 UTC
Labels: Bug
