### ISSUE TITLE
"Files" entry type causing error

### ISSUE THREAD

**Issue by tiurlumbangaol** [xelkano/redmine_xapian#87] opened 2017-12-06 00:32 UTC
Hi,
There is a bug, on the Global search scope, if "files" entry selected.

The behavior for example : 
If i search keyword "this", and "this" keyword is there on repository files,  and i check the "files entry", like this screenshot : 
![image](https://user-images.githubusercontent.com/857816/33638102-02b3ae44-da57-11e7-858f-7bdc266dbc11.png)

then the search result will gave error like this : 
![image](https://user-images.githubusercontent.com/857816/33637747-5b4be7da-da55-11e7-8f0a-13c038980e5a.png)

but if i uncheck the "files" option, the behavior will be normal : 
![image](https://user-images.githubusercontent.com/857816/33638139-33480d66-da57-11e7-92bd-7c8e9e0c3d95.png)

If i search keyword "xyz", and "xyz" keyword is NOT there on repository files,  and i check the "files entry", like this screenshot : 

![image](https://user-images.githubusercontent.com/857816/33638184-62b056bc-da57-11e7-950e-ae8a8c070d11.png)

the behavior will be normal, there is no error.

so the conclusion is, error will happen if search keyword that getting indexed with xapian, and i select the "files" entry option. this bug behavior appears both on : "project scope search" and "global scope search"

**Comment by picman** [comment] 2018-01-05 08:57
I'm afraid that I'm not able to reproduce the error. It works fine for me:

![screenshot-2018-1-5 search - kdp 3 7 webrick](https://user-images.githubusercontent.com/779003/34602028-93ea967a-f1fe-11e7-9eeb-30ab4ee6d3ad.png)

Please post Redmine and the plugin version you are using + production.log.

**Comment by picman** [comment] 2018-01-25 09:49
No feedback => closing.

**Comment by tiurlumbangaol** [comment] 2018-04-02 10:01
hi, 
sorry for the late reply. i was trying to setup new instance, but the error still happened. the log saying : 
`Started GET "/search?utf8=%E2%9C%93&scope=&q=alfresco" for 36.71.134.49 at 2018-04-02 17:00:39 +0000
Processing by SearchController#index as HTML
  Parameters: {"utf8"=>"✓", "scope"=>"", "q"=>"alfresco"}
  Current user: tiur (id=3)
Completed 500 Internal Server Error in 660ms (ActiveRecord: 52.8ms)

NameError (uninitialized constant Article):
  app/models/attachment.rb:171:in `project'
  plugins/redmine_xapian/lib/redmine_xapian/search_strategies/xapian_search.rb:120:in `process_attachment'
  plugins/redmine_xapian/lib/redmine_xapian/search_strategies/xapian_search.rb:102:in `block in xapian_search'
  plugins/redmine_xapian/lib/redmine_xapian/search_strategies/xapian_search.rb:88:in `each'
  plugins/redmine_xapian/lib/redmine_xapian/search_strategies/xapian_search.rb:88:in `xapian_search'
  plugins/redmine_xapian/lib/redmine_xapian/search_strategies/xapian_search_service.rb:30:in `search'
  plugins/redmine_xapian/lib/redmine_xapian/attachment_patch.rb:78:in `search'
  plugins/redmine_xapian/lib/redmine_xapian/attachment_patch.rb:44:in `search_result_ranks_and_ids_with_search_result_ranks_and_ids_ext'
  lib/redmine/search.rb:127:in `block in load_result_ids'
  lib/redmine/search.rb:125:in `each'
  lib/redmine/search.rb:125:in `load_result_ids'
  lib/redmine/search.rb:115:in `block in load_result_ids_from_cache'
  lib/redmine/search.rb:114:in `load_result_ids_from_cache'
  lib/redmine/search.rb:99:in `result_ids'
  lib/redmine/search.rb:70:in `result_count'
  plugins/redmine_xapian/lib/redmine_xapian/search_controller_patch.rb:135:in `index_with_xapian'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


`

please help

**Comment by picman** [comment] 2018-04-03 12:48
Hm, that's strange. The problem is reported from here:
```
NameError (uninitialized constant Article):
app/models/attachment.rb:171:in project' plugins/redmine_xapian/lib/redmine_xapian/search_strategies/xapian_search.rb:120:inprocess_attachment'
```
There is called a Redmine method `Attachment.project` which internally calls `container.try(:project)`. In your case `container` is probably Article. Article very probably comes from a plugin, doesn't it?
I've no clue why it fails here, I'm afraid.
Maybe post the plugin's link and I will try it locally.

**Comment by picman** [comment] 2018-04-04 08:44
'Article' seems to come from Knowledgebase plugin. So I've tested searching with this plugin installed and everything seems to be Okay.

**Comment by tiurlumbangaol** [comment] 2018-04-05 03:15
hi, yes, i also tested it using redmine knowledge base plugin. but it is succesfull. i think because of my previous database.

somehow previous database structure causing error. let me go through it again, and will update it here.

**Comment by tiurlumbangaol** [comment] 2018-04-07 01:31
hi, did you solve it on version 1.6.8?

**Comment by picman** [comment] 2018-04-07 04:32
I haven't solved it. I've just removed the milestone.

**Comment by tiurlumbangaol** [comment] 2018-04-22 06:57
hi @picman 

i have trace it, and i know what the cause is.

i have record in "attachments" table that has "container_type" is Article, and Contacts.

While i already uninstall the article and contacts plugin.

My steps to solve this : 
# get all the "disk_filename" of all attachments, for example i use this query for the contacts attachments : 
`select * from attachments as a, notes as n where a.container_type='Note' and a.`container_id` =n.id and a.`disk_filename` and n.source_type='Contact'
`
# put that full path of query result into a text file, for example : list-of-error-files.txt
# then i delete all documents that listed on "list-of-error-files.txt" by using this command on linux : 
`xargs rm -r < list-of-error-files.txt`

Can you put handling exception for this case? so if that case happened, it will not cause error on redmine_xapian

btw, this is a really really cool plugin. thanks for creating it :)

**Comment by picman** [comment] 2018-04-23 11:30
I've already fixed it in this commit: https://github.com/xelkano/redmine_xapian/commit/8dd19b56e6cf2d08378b569dcf68fb653c71bdab.

**Closed by picman** 2018-04-23 11:30 UTC
Labels: Bug
